// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file hello.proto (package myapp, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloRequest, HelloResponse } from "./hello_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service myapp.GreetingService
 */
export const GreetingService = {
  typeName: "myapp.GreetingService",
  methods: {
    /**
     * @generated from rpc myapp.GreetingService.Hello
     */
    hello: {
      name: "Hello",
      I: HelloRequest,
      O: HelloResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

